CREATE TABLE execucoes_ingestao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    executado_em TIMESTAMP NOT NULL,
    arquivo_origem VARCHAR2(255) NOT NULL,
    registros_lidos NUMBER NOT NULL,
    registros_inseridos NUMBER NOT NULL
);

CREATE TABLE leituras_sensores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_leitura DATE NOT NULL,
    cultura VARCHAR2(40) NOT NULL,
    umidade NUMBER(6,2) NOT NULL,
    ph NUMBER(5,2) NOT NULL,
    n_ok NUMBER(1) NOT NULL,
    p_ok NUMBER(1) NOT NULL,
    k_ok NUMBER(1) NOT NULL,
    chuva_probabilidade NUMBER(6,2) NOT NULL,
    bomba_ligada NUMBER(1) NOT NULL,
    umidade_futura NUMBER(6,2) NOT NULL,
    ph_futuro NUMBER(5,2) NOT NULL,
    volume_irrigacao_l NUMBER(10,2) NOT NULL,
    necessidade_fertilizacao_kg_ha NUMBER(10,2) NOT NULL,
    rendimento_estimado_t_ha NUMBER(10,2) NOT NULL,
    CONSTRAINT uq_leituras_sensores UNIQUE (data_leitura, cultura)
);

CREATE TABLE previsoes_modelo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leitura_id NUMBER NOT NULL,
    modelo VARCHAR2(80) NOT NULL,
    alvo VARCHAR2(80) NOT NULL,
    valor_previsto NUMBER(10,3) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_prev_leitura FOREIGN KEY (leitura_id) REFERENCES leituras_sensores(id)
);

CREATE TABLE recomendacoes_manejo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leitura_id NUMBER NOT NULL,
    acao_irrigacao VARCHAR2(120) NOT NULL,
    acao_ph VARCHAR2(120) NOT NULL,
    acao_nutrientes VARCHAR2(160) NOT NULL,
    risco_produtivo VARCHAR2(80) NOT NULL,
    justificativa VARCHAR2(1000) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_rec_leitura FOREIGN KEY (leitura_id) REFERENCES leituras_sensores(id)
);
